version: '3'

services:
  mongodb:
    container_name: auth-ts-mongodb
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27018
  api:
    container_name: auth-ts
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URL=mongodb://auth-ts-mongodb:27018/auth-ts
      - PORT=5000
    volumes:
      - ./dist:/usr/src/auth-ts/dist/
      - ./package.json:/usr/src/auth-ts/package.json
    ports:
      - 5000:5000
      - 9222:9222
    links:
      - mongodb
